version: "3.8"

services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-123}
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine

  redis-queue:
    image: redis:alpine

  redis-socketio:
    image: redis:alpine

  frappe:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - SHELL=/bin/bash
      - PRODUCTION=1
      - DB_HOST=mariadb
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379
      - SITE_NAME=${SITE_NAME:-hrms.localhost}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-123}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    volumes:
      - frappe-sites-data:/home/frappe/frappe-bench/sites
    ports:
      - 8010:8000
      - 9010:9000
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio

volumes:
  mariadb-data:
  frappe-sites-data:
